services:
  server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./server:/app
    env_file:
      - ./.env
    command: sh -lc "npm i && npm run dev"
    ports:
      - "8787:8787"

  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    env_file:
      - ./.env
    command: sh -lc "npm i && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - server
